- DESCRIPTION
- R/final_size.R
- tests/testthat/test-test_basic_finalsize.R
- tests/testthat/test-test_finalsize_calculations.R
Adding better tests for `finalsize` and `final_size`.
- Fixes #29 by setting lower limit for `r0` at 1.0. Values below this result in a final epidemic size of 0.0.
- Fixes #30 by checking that epidemic final sizes are below `prop_initial_infected` and 1.0 _in each age group_
- Adds tests by @BlackEdder taken from #26 for plausible epidemic sizes
- Adds the helper function `upper_limit` from @BlackEdder from #26 
- Fixes #31 by allow `prop_suscep` to be a single population wide value
> Better tests for finalsize

- src/RcppExports.cpp
- src/finalsize_risk_grps.cpp
- src/test-finalsize_funs.cpp
- src/test-finalsize_grps.cpp
- tests/testthat/test-finalsize_by_group.R
This PR tries to determine why multiple tests fail for `final_size_grps_cpp`. This is done by adding yet more tests to try and determine where failures occur. The best guess currently is numerical instability in `solve_final_size_newton`, which leads to `NaN`s and `0`s returned for final sizes.
> Better tests for final size by susceptibility groups

- tests/testthat/test-iterative_solver_vary_r0.R
Fixing a test for the iterative solver, where the `epi_spread` step had been omitted, leading to the test failing. This should help #63 pass @Bisaloo.
> Fix test for iterative solver, add epi_spread step

- R/iterative_solver.R
- tests/testthat/test-iterative_solver_vary_r0.R
This PR gathers some minor simplifications and performance improvements to the iterative solver.
- 21afdf47b25389f8cccd8113362fc2fa5ee25a71: I use the outer product instead of the Kronecker product. This removes the need to cast as a vector and then recast a matrix, with the associated risks of filling by rows instead of cols, etc. It is also much more efficient:
``` r
x <- matrix(runif(100), nrow = 10)
s <- runif(10)
d <- runif(10)
microbenchmark::microbenchmark(
matrix(as.vector(x) * s %x% d, nrow = nrow(x)),
x * d %o% s,
check = "identical"
)
#> Unit: microseconds
#>                                            expr    min      lq     mean  median
#>  matrix(as.vector(x) * s %x% d, nrow = nrow(x)) 23.129 24.1395 25.45444 24.9135
#>                                     x * d %o% s  4.988 …
```
> Simplify and improve performance of iterative solver

- .github/workflows/test-coverage.yaml
Using `any::XML` in dependencies setup `v2` to fix `XML` compile errors. Errors possibly introduced by reverting to CRAN version of `socialmixr`, which pulls in an older version of `XML` that doesn't compile on R v 4.2.x?
> Fix XML issues

- .github/workflows/test-coverage.yaml
- R/final_size.R
- man/final_size.Rd
- tests/testthat/test-check_output_df.R
- tests/testthat/test-finalsize_grps_cpp_msgs.R
- tests/testthat/test-iterative_solver_mult_grps.R
- tests/testthat/test-iterative_solver_vary_r0.R
- tests/testthat/test-newton_solver_mult_grps.R
This is the result of the discussion we had about user profiles during the LSHTM meeting yesterday. We think that some users will run functions with the defaults and assume that they got a scientifically valid value.
We would like to prevent this kind of situation by forcing the user to explicitly pass a value for r0.
> Remove default value for r0

- .Rbuildignore
- .github/ISSUE_TEMPLATE/bug_report.md
- .lintr
- DESCRIPTION
- R/RcppExports.R
- R/final_size.R
- README.Rmd
- README.md
- cran-comments.md
- src/iterative_solver.cpp
- src/newton_solver.cpp
- tests/testthat/test-iterative_solver_vary_r0.R
This pull request corrects some minor issues with `finalsize` in order to prepare for a CRAN release. This PR includes commits that tackle the checklist in #96, under the "First release" section.
1. https://github.com/epiverse-trace/finalsize/pull/100/commits/b14fc03b760e325a9e9fb3f447436e74c7585008 fixes #101 
2. https://github.com/epiverse-trace/finalsize/pull/100/commits/9f0750ea8cf386c377a726aeee96c14714880770 fixes #102
3. https://github.com/epiverse-trace/finalsize/pull/100/commits/9f0750ea8cf386c377a726aeee96c14714880770, https://github.com/epiverse-trace/finalsize/pull/100/commits/98313a1d4389a28dfeebd95845a72a80de530fee, https://github.com/epiverse-trace/finalsize/pull/100/commits/44b4ae6426f646addf2ae324bcfbea6360a83a58 fixes #103 
4. …
> Minor corrections to finalsize

- DESCRIPTION
- vignettes/finalsize.Rmd
- vignettes/uncertainty_params.Rmd
- vignettes/varying_susceptibility.Rmd
- Correct links from articles to the starter vignette.
- Use png images as svg rendering is bad
> Correct links to starter vignette

- src/iterative_solver.cpp
- src/newton_solver.cpp
Uses `int` instead of `size_t` in loops comparing against matrix sizes; WIP on checks from #96.
> Fix iterator type in solvers

- .github/workflows/Cpp-lint-check.yaml
- DESCRIPTION
- src/iterative_solver.cpp
- src/newton_solver.cpp
This PR implements a few miscellaneous fixes:
1. Corrects the order of URLs in the DESCRIPTION URL field;
2. Use pass-by-reference rather than `std::move` semantics to avoid _Cppcheck_ style warnings;
3. Clarify C++ linting workflow commands.
> Miscellaneous fixes

- .github/workflows/R-CMD-check.yaml
- R/final_size.R
- data-raw/polymod_uk.R
- tests/testthat/test-basic.R
- tests/testthat/test-messages.R
- tests/testthat/test-newton_solver.R
- tests/testthat/test-solver_options.R
- tests/testthat/test-solver_speedups.R
- tests/testthat/test-statistical_correctness.R
- vignettes/finalsize.Rmd
- vignettes/uncertainty_params.Rmd
- vignettes/varying_susceptibility.Rmd
Fixes #131 submitted by @erees. Corrects all cases in which the largest contact matrix eigenvalue is extracted to get the largest _real_ eigenvalue. This PR is being merged into #121 as scaling the contact matrix by the largest real eigenvalue is an important step that is covered in the vignettes.
> Correct examples, vignettes, tests to use real eigenvalues

- .github/workflows/R-CMD-check.yaml
- DESCRIPTION
- R/final_size.R
- README.Rmd
- README.md
- data-raw/polymod_uk.R
- man/final_size.Rd
- tests/testthat/test-basic.R
- tests/testthat/test-messages.R
- tests/testthat/test-newton_solver.R
- tests/testthat/test-solver_options.R
- tests/testthat/test-solver_speedups.R
- tests/testthat/test-statistical_correctness.R
- vignettes/finalsize.Rmd
- vignettes/references.bib
- vignettes/uncertainty_params.Rmd
- vignettes/varying_susceptibility.Rmd
This pull request:
1. Fixes #117 by replacing the development version installation instructions,
2. Fixes #118 by changing the order of `susceptibility` and `p_susceptibility` in the function call, and in documentation,
3. Fixes #122 by removing package installation step from 'Getting started' (vignettes/finalsize.Rmd),
4. Fixes #123 by checking for package installation before loading; removes `{data.table}` use,
5. Fixes #124 by changing the POLYMOD reference link to the PLOS Medicine paper,
6. Fixes #125 by changing age group notation in vignette text,
7. Fixes #127 by printing input and output to screen in the basic vignette.
8. Fixes #130 by adding a section on sources and patterns of heterogeneous susceptibility, and a box on getting data on these patterns
Additionally fixes #131 by …
> Improve documentation and argument order

- README.Rmd
- README.md
- _pkgdown.yml
- vignettes/finalsize.Rmd
- vignettes/uncertainty_params.Rmd
- vignettes/varying_contacts.Rmd
- vignettes/varying_susceptibility.Rmd
This PR fixes #142 and also simplifies the "Get started" vignette (`finalsize.Rmd`), to show an example _without_ age-stratified social contact patterns, and with a single population-wide susceptibility to infection.
This is likely to provide an easier entry point for users than the previous contents, which are now moved to their own vignette, "Modelling heterogeneous social contacts".
This PR also:
1. Uses an $R_0$ value of 1.5 (pandemic influenza) in all cases,
2. Adds links to earlier vignettes where required,
3. Adds an example showing how heterogeneous susceptibility can be modelled without also including heterogeneous social contacts.
4. Fixes #116 again by editing the Readme.
> Simplify "Get started" vignette

- README.Rmd
- README.md
- _pkgdown.yml
This PR aims to fix #147 by rendering the development version of the website and linking it from the Readme.
> Render dev version of website

- .gitattributes
Ignore the vignettes/ directory when calculating repository language statistics. Prevents over-representation of languages used to write the vignettes (here, R), as well as inclusion of languages that do not influence the package code (here, LaTeX, from the references stored as a .bib file).
> Ignore vignettes for repo langs stats

- DESCRIPTION
The same way we don't include pkgdown in `Suggests`, we shouldn't include covr or usethis, which are only used as part of a user-invisible development process. This also removes some of the reverse dependency checking burden for these packages.
> Remove pkgs used only in development

- README.Rmd
- README.md
- vignettes/finalsize.Rmd
Talking to people interested in epidemic risk has reiterated that one of the big advantages of finalsize is the relatively few parameters that need defining (e.g. to estimate final size in _epidemics_ requires the user to define many more parameters, and hence do literature searches etc.) Have made some tweaks to description so this advantage/differentiation is stated more clearly in the foreground.
**Please check if the PR fulfills these requirements**
- [ X ] I have read the CONTRIBUTING guidelines 
- [ -] A new item has been added to `NEWS.md` – Not included as this PR is only small copy changes in documentation rather than any functionality/code changes.
- [X ] Tests for the changes have been added (for bug fixes / features)
- [ X] Docs have been added / updated (for bug fixes / …
> Update README and Get started

- R/final_size.R
- README.Rmd
- README.md
- man/final_size.Rd
- tests/testthat/test-basic.R
- vignettes/finalsize.Rmd
This PR fixes #180 by providing default values for all population parameters in `final_size()`.
This allows final size calculation given only the epidemic $R_0$, assuming a homogeneously mixing population with full susceptibility, e.g.:
```r
final_size(1.3)
```
> Add defaults to final_size()

- CITATION.cff
- DESCRIPTION
- NEWS.md
- inst/WORDLIST
- revdep/README.md
- revdep/cran.md
- vignettes/demographic_turnover.Rmd
- vignettes/theoretical_background.Rmd
- vignettes/varying_susceptibility.Rmd
This PR increments the package version to v0.2.1. This is aimed at getting fixes to #180 in to the CRAN release (see #201), as well as updating the release version of the website with the theoretical background and demographic turnover vignettes.
> Release patch v0.2.1

- .github/workflows/test-coverage.yaml
This PR updates the test coverage workflow to re-allow uploading coverage results to Codecov.
> Update test coverage workflow with global Codecov token

- .github/workflows/R-CMD-check.yaml
- .github/workflows/dependency-change.yaml
- .github/workflows/lint-changed-files.yaml
- .github/workflows/pkgdown.yaml
- .github/workflows/render_readme.yml
- .github/workflows/update-citation-cff.yaml
- .github/workflows/update-copyright-year.yml
- DESCRIPTION
- LICENSE
- LICENSE.md
- NEWS.md
- R/dev-utils.R
- README.md
- inst/WORDLIST
- man/finalsize-package.Rd
- tests/testthat/test-dev-utils.R
- tools/check.env
- touchstone/script.R
- vignettes/demographic_turnover.Rmd
- vignettes/finalsize.Rmd
- vignettes/uncertainty_params.Rmd
This PR cleans up {finalsize} to prepare for a handover.
> Mid year cleanup

- NEWS.md
- R/final_size.R
- man/final_size.Rd
- tests/testthat/_snaps/statistical_correctness.md
- tests/testthat/test-basic.R
- tests/testthat/test-statistical_correctness.R
- vignettes/finalsize.Rmd
Hi @adamkucharski, I had some time on my hands and this seemed like an easy request by @BlackEdder so I'm just popping this PR in. I've updated one vignette but there may be other instances where the new output could simplify code.
* **Please check if the PR fulfills these requirements**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
This PR aims to fix #219 by:
1. Returning the demography-susceptibility group sizes as part of `final_size()` output; these are already [calculated in the function as `demography_vector_spread`](https://github.com/epiverse-trace/finalsize/blob/4addd753bf06bd59cf677ce443fab9d885418797/R/final_size.R#L217).
2. Additionally, provides the `n_infected` column for the product of group size and `p_infected`, as this is the end …
> Return demography-susceptibility group sizes and N infected

- NEWS.md
- R/final_size.R
- R/r0_conversions.R
- _pkgdown.yml
- inst/WORDLIST
- man/final_size.Rd
- man/r0_conversions.Rd
- tests/testthat/test-contact_scaling.R
- vignettes/r_eff_reckoner.Rmd
* **Please check if the PR fulfills these requirements**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
This PR is WIP on #220 since I had some time and this functionality would be generally useful. cc-ing @adamkucharski  and @ellen-is for feedback.
1. Added a `contact_scaling` argument to `final_size()` and `r_eff()` that allows uniform or group-wise scaling of social contacts; defaults to 1.0 for no scaling. It would be worth checking that the contacts scaling is done correctly, and that overall this is what the issue requires.
2. Added tests and documentation for the new argument;
3. Added a new vignette aiming to make plot similar to https://github.com/ellen-is/reckoners. The vignette figures don't include any uncertainty as I haven't added any …
> Add contact scaling functionality
